# Generated by Django 3.2.10 on 2022-02-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=220)),
                ('cardNumber', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=6)),
                ('balance', models.CharField(max_length=20)),
            ],
        ),
    ]
