# Generated by Django 3.2.10 on 2022-02-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cardNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
